In [2]:
import numpy as np

In [3]:
b = np.linspace(0,101,101)
print(b)
print(b.shape)

[  0.     1.01   2.02   3.03   4.04   5.05   6.06   7.07   8.08   9.09
  10.1   11.11  12.12  13.13  14.14  15.15  16.16  17.17  18.18  19.19
  20.2   21.21  22.22  23.23  24.24  25.25  26.26  27.27  28.28  29.29
  30.3   31.31  32.32  33.33  34.34  35.35  36.36  37.37  38.38  39.39
  40.4   41.41  42.42  43.43  44.44  45.45  46.46  47.47  48.48  49.49
  50.5   51.51  52.52  53.53  54.54  55.55  56.56  57.57  58.58  59.59
  60.6   61.61  62.62  63.63  64.64  65.65  66.66  67.67  68.68  69.69
  70.7   71.71  72.72  73.73  74.74  75.75  76.76  77.77  78.78  79.79
  80.8   81.81  82.82  83.83  84.84  85.85  86.86  87.87  88.88  89.89
  90.9   91.91  92.92  93.93  94.94  95.95  96.96  97.97  98.98  99.99
 101.  ]
(101,)


In [4]:
sigma = 0.5
space_mesh_division = 101
B = np.diagflat([sigma for i in range(space_mesh_division - 1)], -1) +\
        np.diagflat([1 - 2 * sigma for i in range(space_mesh_division)]) +\
        np.diagflat([sigma for i in range(space_mesh_division - 1)], 1)
print(B)
print(B.shape)

[[0.  0.5 0.  ... 0.  0.  0. ]
 [0.5 0.  0.5 ... 0.  0.  0. ]
 [0.  0.5 0.  ... 0.  0.  0. ]
 ...
 [0.  0.  0.  ... 0.  0.5 0. ]
 [0.  0.  0.  ... 0.5 0.  0.5]
 [0.  0.  0.  ... 0.  0.5 0. ]]
(101, 101)


In [5]:
b[1:-1]

array([ 1.01,  2.02,  3.03,  4.04,  5.05,  6.06,  7.07,  8.08,  9.09,
       10.1 , 11.11, 12.12, 13.13, 14.14, 15.15, 16.16, 17.17, 18.18,
       19.19, 20.2 , 21.21, 22.22, 23.23, 24.24, 25.25, 26.26, 27.27,
       28.28, 29.29, 30.3 , 31.31, 32.32, 33.33, 34.34, 35.35, 36.36,
       37.37, 38.38, 39.39, 40.4 , 41.41, 42.42, 43.43, 44.44, 45.45,
       46.46, 47.47, 48.48, 49.49, 50.5 , 51.51, 52.52, 53.53, 54.54,
       55.55, 56.56, 57.57, 58.58, 59.59, 60.6 , 61.61, 62.62, 63.63,
       64.64, 65.65, 66.66, 67.67, 68.68, 69.69, 70.7 , 71.71, 72.72,
       73.73, 74.74, 75.75, 76.76, 77.77, 78.78, 79.79, 80.8 , 81.81,
       82.82, 83.83, 84.84, 85.85, 86.86, 87.87, 88.88, 89.89, 90.9 ,
       91.91, 92.92, 93.93, 94.94, 95.95, 96.96, 97.97, 98.98, 99.99])

In [6]:
b[1:-1] = B[1:-1].dot(20 + np.zeros(space_mesh_division))
print(b)

[  0.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.
  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.
  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.
  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.
  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.
  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.
  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.  20.
  20.  20. 101.]


In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = np.zeros(3)+10
print(a)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10. 10. 10.]


In [ ]:
d = a.dot(c)

In [ ]:
d[0]

In [8]:
d[-1]

NameError: name 'd' is not defined

In [ ]:
d[-2]

In [ ]:
d[0:-1]

In [9]:
A = (15,22)
B,C = A
print(B)
print(C)

15
22
